# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /export/johann/fdf-dbg_so/membrain-4.2/membrain/server/sdf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /export/johann/fdf-dbg_so/membrain-4.2/membrain/server/sdf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /export/johann/fdf-dbg_so/membrain-4.2/membrain/server/sdf/CMakeFiles /export/johann/fdf-dbg_so/membrain-4.2/membrain/server/sdf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /export/johann/fdf-dbg_so/membrain-4.2/membrain/server/sdf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fdfdbg

# Build rule for target.
fdfdbg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdfdbg
.PHONY : fdfdbg

# fast build rule for target.
fdfdbg/fast:
	$(MAKE) -f CMakeFiles/fdfdbg.dir/build.make CMakeFiles/fdfdbg.dir/build
.PHONY : fdfdbg/fast

#=============================================================================
# Target rules for targets named agent

# Build rule for target.
agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agent
.PHONY : agent

# fast build rule for target.
agent/fast:
	$(MAKE) -f agent/CMakeFiles/agent.dir/build.make agent/CMakeFiles/agent.dir/build
.PHONY : agent/fast

#=============================================================================
# Target rules for targets named api

# Build rule for target.
api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api
.PHONY : api

# fast build rule for target.
api/fast:
	$(MAKE) -f api/CMakeFiles/api.dir/build.make api/CMakeFiles/api.dir/build
.PHONY : api/fast

#=============================================================================
# Target rules for targets named ecc

# Build rule for target.
ecc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecc
.PHONY : ecc

# fast build rule for target.
ecc/fast:
	$(MAKE) -f ecc/CMakeFiles/ecc.dir/build.make ecc/CMakeFiles/ecc.dir/build
.PHONY : ecc/fast

#=============================================================================
# Target rules for targets named fth

# Build rule for target.
fth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fth
.PHONY : fth

# fast build rule for target.
fth/fast:
	$(MAKE) -f fth/CMakeFiles/fth.dir/build.make fth/CMakeFiles/fth.dir/build
.PHONY : fth/fast

#=============================================================================
# Target rules for targets named misc

# Build rule for target.
misc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc
.PHONY : misc

# fast build rule for target.
misc/fast:
	$(MAKE) -f misc/CMakeFiles/misc.dir/build.make misc/CMakeFiles/misc.dir/build
.PHONY : misc/fast

#=============================================================================
# Target rules for targets named platform

# Build rule for target.
platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platform
.PHONY : platform

# fast build rule for target.
platform/fast:
	$(MAKE) -f platform/CMakeFiles/platform.dir/build.make platform/CMakeFiles/platform.dir/build
.PHONY : platform/fast

#=============================================================================
# Target rules for targets named hotkey

# Build rule for target.
hotkey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hotkey
.PHONY : hotkey

# fast build rule for target.
hotkey/fast:
	$(MAKE) -f platform/tool/hotkey/CMakeFiles/hotkey.dir/build.make platform/tool/hotkey/CMakeFiles/hotkey.dir/build
.PHONY : hotkey/fast

#=============================================================================
# Target rules for targets named protocol

# Build rule for target.
protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocol
.PHONY : protocol

# fast build rule for target.
protocol/fast:
	$(MAKE) -f protocol/CMakeFiles/protocol.dir/build.make protocol/CMakeFiles/protocol.dir/build
.PHONY : protocol/fast

#=============================================================================
# Target rules for targets named action

# Build rule for target.
action: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 action
.PHONY : action

# fast build rule for target.
action/fast:
	$(MAKE) -f protocol/action/CMakeFiles/action.dir/build.make protocol/action/CMakeFiles/action.dir/build
.PHONY : action/fast

#=============================================================================
# Target rules for targets named home

# Build rule for target.
home: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 home
.PHONY : home

# fast build rule for target.
home/fast:
	$(MAKE) -f protocol/home/CMakeFiles/home.dir/build.make protocol/home/CMakeFiles/home.dir/build
.PHONY : home/fast

#=============================================================================
# Target rules for targets named replication

# Build rule for target.
replication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 replication
.PHONY : replication

# fast build rule for target.
replication/fast:
	$(MAKE) -f protocol/replication/CMakeFiles/replication.dir/build.make protocol/replication/CMakeFiles/replication.dir/build
.PHONY : replication/fast

#=============================================================================
# Target rules for targets named sdftcp

# Build rule for target.
sdftcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdftcp
.PHONY : sdftcp

# fast build rule for target.
sdftcp/fast:
	$(MAKE) -f sdftcp/CMakeFiles/sdftcp.dir/build.make sdftcp/CMakeFiles/sdftcp.dir/build
.PHONY : sdftcp/fast

#=============================================================================
# Target rules for targets named sdfmsg

# Build rule for target.
sdfmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdfmsg
.PHONY : sdfmsg

# fast build rule for target.
sdfmsg/fast:
	$(MAKE) -f sdfmsg/CMakeFiles/sdfmsg.dir/build.make sdfmsg/CMakeFiles/sdfmsg.dir/build
.PHONY : sdfmsg/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f utils/CMakeFiles/utils.dir/build.make utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named ssd

# Build rule for target.
ssd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssd
.PHONY : ssd

# fast build rule for target.
ssd/fast:
	$(MAKE) -f ssd/CMakeFiles/ssd.dir/build.make ssd/CMakeFiles/ssd.dir/build
.PHONY : ssd/fast

#=============================================================================
# Target rules for targets named clipper

# Build rule for target.
clipper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipper
.PHONY : clipper

# fast build rule for target.
clipper/fast:
	$(MAKE) -f ssd/clipper/CMakeFiles/clipper.dir/build.make ssd/clipper/CMakeFiles/clipper.dir/build
.PHONY : clipper/fast

#=============================================================================
# Target rules for targets named fifo

# Build rule for target.
fifo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fifo
.PHONY : fifo

# fast build rule for target.
fifo/fast:
	$(MAKE) -f ssd/fifo/CMakeFiles/fifo.dir/build.make ssd/fifo/CMakeFiles/fifo.dir/build
.PHONY : fifo/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) -f shared/CMakeFiles/shared.dir/build.make shared/CMakeFiles/shared.dir/build
.PHONY : shared/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fdfdbg"
	@echo "... rebuild_cache"
	@echo "... agent"
	@echo "... api"
	@echo "... ecc"
	@echo "... fth"
	@echo "... misc"
	@echo "... platform"
	@echo "... hotkey"
	@echo "... protocol"
	@echo "... action"
	@echo "... home"
	@echo "... replication"
	@echo "... sdftcp"
	@echo "... sdfmsg"
	@echo "... utils"
	@echo "... ssd"
	@echo "... clipper"
	@echo "... fifo"
	@echo "... shared"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

