#!/bin/bash
# Run a test.

S=/opt/schooner

Z=$S/openmpi-1.3/lib
Z=$Z:$S/CUnit-2.1-0/lib
Z=$Z:$S/dmalloc-5.5.2/lib
Z=$Z:$S/fuse/lib
Z=$Z:$S/gcc-4.3.1/lib64
export LD_LIBRARY_PATH=$Z

Z=$S/valgrind-3.3.1/bin
Z=$Z:$S/openmpi-1.3/bin
Z=$Z:$S/dmalloc-5.5.2/bin
Z=$Z:$S/gcc-4.3.1/bin
Z=$Z:/bin
Z=$Z:/usr/bin
export PATH=$Z

export PROPERTIES_FILE=../../../config/schooner-med.properties

mpirun -np 2 "$@" -d -y
