# $Id$
TOP = ../../..

include $(TOP)/Makefile.defs

LIB_SRCS = \
	fifo.c \
	mcd_aio.c \
	mcd_bak.c \
	mcd_pfx.c \
	mcd_rec.c \
	mcd_rep.c \
	mcd_sync.c \
	mcd_hash.c \
 	mcd_osd.c \
	recovery.c 

LIB = libfifo.a

#SUBDIRS = \
#	tests

include $(TOP)/Makefile.inc

