# $Id: Makefile 7475 2009-05-20 21:03:59Z tomr $

TOP = ../../../..


LIB = libhotkey.a
LIB_SRCS = \
	ht_report.c 	\
	ht_snapshot.c	\
	ht_alloc.c		

SUBDIRS=tests

include $(TOP)/Makefile.inc

#CPPFLAGS += -DCONFIG_TEST_SUPPORT

