#!/bin/bash -ue

# Ensure FDF_LIB is set
if [ -z "${FDF_LIB-}" ]; then
    echo >&2 "First set FDF_LIB to the FDF shared library; such as"
    echo >&2 "  export FDF_LIB=/tmp/libfdfdbg.so"
    echo >&2 "  ./hello"
    echo >&2 "or"
    echo >&2 "  FDF_LIB=/tmp/libfdfdbg.so ./hello"
    exit 1
fi

# Make DLL library
cd ..
make

# Make hello
cd test
make

export FDF_PROPERTY_FILE=./property_file
./hello
