# sdfmt is the SDF Message Transport library
# 
#
# The libsdfmtp.lib is used for the underlying transport mechanism
# for sdf messaging
# ------------------------------------------------------------------
# 


TOP = ../..

LIB = libsdfmtp.a

LIB_SRCS = \
	msg_int.c \
	msg_map.c \
	msg_msg.c \
	locks.c \
	stats.c \
	tools.c \
	trace.c

# bypass until a functional test is in place
# SUBDIRS = tests

include $(TOP)/Makefile.inc
