# $Id: Makefile 5362 2008-12-31 21:50:42Z jim $

TOP = ../../..
LIBS = \
	$(TOP)/sdf/misc/libmisc.a \
	$(TOP)/sdf/platform/libplatform.a \
	$(TOP)/sdf/utils/libutils.a \
	-lpthread

PROG = shmemd

include $(TOP)/Makefile.inc
