# $Id: Makefile 226 2008-02-08 23:17:26Z darpan $

TOP = ../..
LIB = libutils.a
LIB_SRCS = \
	linkedlist.c \
	hash.c \
	hashmap.c \
	properties.c \
	rtlog.c \
	stats.c \
	stats2.c \
	caller.c \
	sdfkey.c \
	platform_check.c

SUBDIRS = tests

include $(TOP)/Makefile.pre

include $(TOP)/Makefile.post
