# $Id: Makefile 1500 2008-06-06 02:06:33Z drew $

TOP = ../../..

LIB = libsdfreplication.a

LIB_SRCS = \
	copy_replicator.c \
	copy_replicator_meta.c \
	copy_replicator_misc.c \
	key_lock.c \
	meta.c \
	meta_storage.c \
	replicator.c \
	replicator_adapter.c\
	sdf_vips.c \
	rpc.c

#SUBDIRS = tests

include $(TOP)/Makefile.inc
