# $Id: Makefile 9983 2009-11-02 18:25:23Z gxu $

TOP = ../..

LIBS =

# libsdfagent is linked against by client code and PROG sdfagent 
LIB = libsdfagent.a

LIB_SRCS = \
	agent_helper.c \
	agent_sm.c

USE_MPI = 1

include $(TOP)/Makefile.inc
