#ifndef LFSR_H
#define LFSR_H 1

/*
 * File:   lfsr.h
 * Author: Guy Shaw
 *
 * Created on August 29, 2008
 *
 * (c) Copyright 2008, Schooner Information Technology, Inc.
 * http://www.schoonerinfotech.com/
 *
 * $Id: $
 */

#include <stddef.h>             // Import size_t

/**
 * @brief Support functions for Linear Feedback Shift Register
 */

/**
 * @brief Select a primitive polynomial to seed a LFSR suitable
 * for producing a sequence of the given length.
 *
 * A sequence of any length can be generated by using the polynomial
 * for the next power of 2, then ignoring excess generated values
 * that fall outside the range, 0 .. length - 1, inclusive.
 *
 */
extern unsigned int
lfsr_seed(size_t len);

/**
 * @brief Fill a buffer with characters generated by a maximal length LSFR.
 */
extern void
lfsr_fill(unsigned char *buf, size_t size, unsigned int lbound, unsigned int hbound);

#endif /* ndef LFSR_H */
