//----------------------------------------------------------------------------
// ZetaScale
// Copyright (c) 2016, SanDisk Corp. and/or all its affiliates.
//
// This program is free software; you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License version 2.1 as published by the Free
// Software Foundation;
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License v2.1 for more details.
//
// A copy of the GNU Lesser General Public License v2.1 is provided with this package and
// can also be found at: http://opensource.org/licenses/LGPL-2.1
// You should have received a copy of the GNU Lesser General Public License along with
// this program; if not, write to the Free Software Foundation, Inc., 59 Temple
// Place, Suite 330, Boston, MA 02111-1307 USA.
//----------------------------------------------------------------------------

#ifndef LFSR_H
#define LFSR_H 1

/*
 * File:   lfsr.h
 * Author: Guy Shaw
 *
 * Created on August 29, 2008
 *
 * (c) Copyright 2008, Schooner Information Technology, Inc.
 * http://www.schoonerinfotech.com/
 *
 * $Id: $
 */

#include <stddef.h>             // Import size_t

/**
 * @brief Support functions for Linear Feedback Shift Register
 */

/**
 * @brief Select a primitive polynomial to seed a LFSR suitable
 * for producing a sequence of the given length.
 *
 * A sequence of any length can be generated by using the polynomial
 * for the next power of 2, then ignoring excess generated values
 * that fall outside the range, 0 .. length - 1, inclusive.
 *
 */
extern unsigned int
lfsr_seed(size_t len);

/**
 * @brief Fill a buffer with characters generated by a maximal length LSFR.
 */
extern void
lfsr_fill(unsigned char *buf, size_t size, unsigned int lbound, unsigned int hbound);

#endif /* ndef LFSR_H */
